#!/usr/bin/env bash
# A Bash script that displays a list of currently running processes in a user-oriented format with hierarchy
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
